." Created by Ian Burgwin.
.TH "NH-MAN-PAGES" 1 "2018-11-19" "Nintendo Homebrew"
.SH NAME
nh-man-pages \- lists custom Nintendo Homebrew man pages
.SH SYNOPSIS
.B nh-man-pages
.SH DESCRIPTION
.B nh-man-pages
lists the custom man pages created for Nintendo Homebrew.
It searches directories in the manpath that start with
.I /opt/nintendohomebrew
and lists filenames under each
.I man/man[0-9]
directory.
.SH SEE ALSO
.BR manpath (1)
