." Created by Ian Burgwin.
.TH "NH-STATUS" 1 "2019-10-29" "Nintendo Homebrew"
.SH NAME
nh-status \- print status of Nintendo Homebrew services
.
.SH SYNOPSIS
.PD 0
.B nh-status
.PD
.
.SH DESCRIPTION
.B nh-status
is used to check the status of Nintendo Homebrew services.
.PP
This is an alias for the
.B status
subcommand of 
.BR nhctl (1).
