." Created by Ian Burgwin.
.TH "NH-HELP" 7 "2018-11-21" "Nintendo Homebrew"
.SH NAME
nh-help \- getting started on using the Nintendo Homebrew VPS
.SH DESCRIPTION
This guide lists the most common commands and features used.
.SS I don't know how to use man!
If you don't know how to navigate \fBman\fP, press q to close this program, then enter the command `\fBman nh-man\fP' to learn more about how to use \fBman\fP.
.PP
Most custom commands are aliases.
If you have changed your default shell from \fI/bin/bash\fP, you should source or check the contents of \fI/opt/nintendohomebrew/etc/bash_aliases\fP.
.PP
Most of these commands have manual pages of their own.
Please check them for more information.
.SH COMMANDS
.TP
.B nhctl
Controls various Nintendo Homebrew services.
Check
.BR nhctl (1)
for more information.
.TP
.B nh-logs
Changes directory to logs.
Check
.BR nh-logs (1)
for more information.
.TP
.B nh-man-pages
Prints the list of custom man pages for Nintendo Homebrew.
